name: tresss
description: A multiplayer Tic-Tac-Toe game built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/game_font.ttf 